# ============================================================
# mpv config - Tokyo Night
# ============================================================

### General
profile=gpu-hq
vo=gpu-next
gpu-context=wayland
hwdec=vaapi
save-position-on-quit=yes
keep-open=yes
autofit-larger=80%

### OSD Tokyo Night
osd-color="#c0caf5"
osd-border-color="#1a1b26"
osd-border-size=1.5
osd-font="JetBrainsMono Nerd Font"
osd-font-size=28
osd-msg1=""
osd-msg2=""
osd-msg3=""
osd-fractions=no
osd-bar-align-y=0.96
osd-bar-h=2
osd-bar-w=60
osd-bar-color="#7aa2f7"

### Subtitles Tokyo Night
sub-color="#c0caf5"
sub-border-color="#1a1b26"
sub-border-size=1.5
sub-shadow-color="#1a1b26"
sub-shadow-offset=1
sub-font="JetBrainsMono Nerd Font"
sub-font-size=22
sub-bold=no
sub-ass-force-style=Kerning=yes
sub-ass-force-style=Outline=0
sub-ass-force-style=BorderStyle=3

### Screenshots
screenshot-format=png
screenshot-high-bit-depth=no
screenshot-directory=~/Pictures/Screenshots
screenshot-template=mpv-%F-%T

### Scripts
script-opts-append=osc-layout=box
script-opts-append=osc-seekbarh=auto
