# ============================================================
# Powerlevel10k - Tokyo Night Colors
# ============================================================
# Para usar: Copia a ~/.p10k.zsh o ~/.config/p10k.zsh
# y en .zshrc:  source ~/.p10k.zsh
# ============================================================

# Colors
P9K_TOKYO_BG="#1a1b26"
P9K_TOKYO_SURFACE="#24283b"
P9K_TOKYO_FG="#c0caf5"
P9K_TOKYO_BLUE="#7aa2f7"
P9K_TOKYO_PURPLE="#bb9af7"
P9K_TOKYO_GREEN="#9ece6a"
P9K_TOKYO_RED="#f7768e"
P9K_TOKYO_YELLOW="#e0af68"
P9K_TOKYO_CYAN="#7dcfff"

# Prompt
POWERLEVEL9K_MODE=nerdfont-v3
POWERLEVEL9K_ICON_PADDING=none

# Left prompt segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
# Right prompt segments
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time)

# OS Icon
POWERLEVEL9K_OS_ICON_BACKGROUND="$P9K_TOKYO_BLUE"
POWERLEVEL9K_OS_ICON_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''

# Context
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="$P9K_TOKYO_SURFACE"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="$P9K_TOKYO_CYAN"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="$P9K_TOKYO_RED"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'

# Directory
POWERLEVEL9K_DIR_BACKGROUND="$P9K_TOKYO_BLUE"
POWERLEVEL9K_DIR_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_DIR_MAX_LENGTH=60

# VCS (Git)
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="$P9K_TOKYO_GREEN"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="$P9K_TOKYO_YELLOW"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="$P9K_TOKYO_RED"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$P9K_TOKYO_BG"

# Status
POWERLEVEL9K_STATUS_OK_BACKGROUND="$P9K_TOKYO_GREEN"
POWERLEVEL9K_STATUS_OK_FOREGROUND="$P9K_TOKYO_BG"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$P9K_TOKYO_RED"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="$P9K_TOKYO_BG"

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="$P9K_TOKYO_PURPLE"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$P9K_TOKYO_BG"

# Background jobs
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="$P9K_TOKYO_YELLOW"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="$P9K_TOKYO_BG"

# Time
POWERLEVEL9K_TIME_BACKGROUND="$P9K_TOKYO_SURFACE"
POWERLEVEL9K_TIME_FOREGROUND="$P9K_TOKYO_FG"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

# Transient prompt
POWERLEVEL9K_TRANSIENT_PROMPT=same-directory
